run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - misspell
    - gocyclo
    - revive

linters-settings:
  gocyclo:
    min-complexity: 15

  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0